### ISSUE TITLE
use dd instead of rm to ensure the drive is wiped

### ISSUE THREAD

**Issue by Martmists-GH** [tiagoad/suicide-linux#6] opened 2018-11-12 10:26 UTC

**Comment by nickwebha** [comment] 2019-02-08 18:15
First `rm`, then random data, then `dd`.

Of course the fastest one first.

**Comment by var-username** [comment] 2019-03-20 20:56
`r`andom
`m`istake? 

`d`estroy
`d`isk. 

Evil. I like it.

**Comment by amyipdev** [comment] 2021-02-24 21:55
Nah. Leave the old partition table there. This way, we can deter the Windows users who don't know how to repartition a disk. :)

**Comment by tiagoad** [comment] 2022-08-19 14:24
I'm not sure this will work as intended in docker. I'm leaving `rm`, but thanks for opening the issue, sorry about closing so late.

**Closed as completed** 2022-08-19 14:24 UTC

**Comment by amyipdev** [comment] 2022-09-24 00:31
@tiagoad would it be possible to change the close type from completed to wontfix?
